version: '3.1'

services:
  eng-elasticsearch:
    container_name: elas-tutorial
    image: engcom.azurecr.io/docker.elastic.co/elasticsearch/elasticsearch
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: vanphudh2003
      discovery.type: single-node
    networks:
      - my-network

#  eng-kibana:
#    container_name: kibana-tutorial
#    image: engcom.azurecr.io/docker.elastic.co/kibana/kibana
#    ports:
#      - "5601:5601"
#    networks:
#      - my-network
#    depends_on:
#      - eng-elasticsearch

  eng-mysql:
    container_name: eng-mysql
    image: engcom.azurecr.io/mysql
    restart: always
    environment:
      MYSQL_DATABASE: english_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

#  eng-pma:
#    container_name: eng_pma
#    image: engcom.azurecr.io/phpmyadmin
#    restart: always
#    ports:
#      - "7000:80"
#    networks:
#      - my-network
#    environment:
#      - PMA_ARBITRARY=1

  eng-redis:
    container_name: redis-tutorial
    image: engcom.azurecr.io/redis
    ports:
      - "6380:6379"
    networks:
      - my-network
  eng-app:
    image: engcom.azurecr.io/englishappapi-eng-app
    container_name: eng-container
    ports:
      - "8080:8080"
    depends_on:
      - eng-elasticsearch
      - eng-redis
      - eng-mysql
    environment:
      MYSQL_HOST: eng-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      REDIS_HOST: redis-tutorial
      REDIS_PORT: 6379
      ELASTICSEARCH_HOST: elas-tutorial
      ELASTICSEARCH_PORT: 9200
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
    networks:
      - my-network
volumes:
  mysql-data:
  elasticsearch:

networks:
  my-network:
    driver: bridge