version: '3.1'

services:
  elasticsearch:
    container_name: elas-tutorial
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: vanphudh2003
      discovery.type: single-node
    networks:
      - my-network

  kibana:
    container_name: kibana-tutorial
    image: docker.elastic.co/kibana/kibana:7.15.1
    ports:
      - "5601:5601"
    networks:
      - my-network
    depends_on:
      - elasticsearch

  mysql:
    container_name: english_app_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: english_db
      MYSQL_USER: phudhs
      MYSQL_PASSWORD: 123456
    ports:
      - "3309:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "7000:80"
    networks:
      - my-network
    environment:
      - PMA_ARBITRARY=1

  redis:
    container_name: redis-tutorial
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - my-network

volumes:
  mysql-data:
  elasticsearch:

networks:
  my-network:
    driver: bridge